sudo: required
language: go

go:
  - 1.9.x


services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - echo "Please don't go get"

script:
  - make test
  - make build

after_success:
  - if [ ! -s "$TRAVIS_TAG" ] ; then
      docker tag functions/openfaas-operator:latest functions/openfaas-operator:$TRAVIS_TAG;
      echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
      docker push functions/openfaas-operator:$TRAVIS_TAG;

      docker tag $DOCKER_NS/openfaas-operator:latest-dev quay.io/$DOCKER_NS/openfaas-operator:$TRAVIS_TAG;
      echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
      docker push quay.io/$DOCKER_NS/openfaas-operator:$TRAVIS_TAG;
    fi
